Inteligentny Organizator Plik├│w: LlmClient Class Reference
LlmClient Class Reference
Klasa do komunikacji z lokalnym modelem LLM przez REST API.
#include <llmclient.h>
Signals
void scriptReady (const QString &script)
void errorOccurred (const QString &error)
Public Member Functions
LlmClient (QObject *parent=nullptr)
Konstruktor.
void generateScript (const QString &userPrompt, const QString &folderPath, const QString &os)
Wygeneruj skrypt na podstawie promptu.
Private Attributes
QNetworkAccessManager * manager
const QString API_URL = "http://localhost:11434/api/generate"
const QString MODEL = "SpeakLeash/bielik-11b-v3.0-instruct:Q4_K_M"
Detailed Description
Klasa do komunikacji z lokalnym modelem LLM przez REST API.
Wysy│a prompt (system + user) i emituje sygna│y z wynikiem.
MAPOWANIE KRYTERIėW:
Komunikacja z modelem lokalnym (Ollama) przez REST API: implementacja w generateScript() (llmclient.cpp).
Definicja system prompt oraz user prompt: budowane w generateScript() (llmclient.cpp).
Dzia│anie bez internetu / obs│uga niedostĻpno£ci: timeout i sprawdzanie b│Ļd¾w QNetworkReply -> emit errorOccurred.
Doxygen: komentarze dokumentuj╣ce klasĻ i funkcje (spe│nia wym¾g dokumentacji).
Definition at line 20 of file llmclient.h.
Constructor & Destructor Documentation
LlmClient()
LlmClient::LlmClient (QObject * parent = nullptr) explicit
Konstruktor.
Konstruktor LlmClient.
Parameters
parent rodzic QObject
Definition at line 13 of file llmclient.cpp.
                                    : QObject(parent)
{
    manager = new QNetworkAccessManager(this);
}
References manager.
Member Function Documentation
errorOccurred
void LlmClient::errorOccurred (const QString & error) signal
Emitted on error with human-readable message.
Referenced by generateScript(), MainWindow::MainWindow(), and FileOrganizerTests::test_llmClient_emitsError_whenNoOllama().
generateScript()
void LlmClient::generateScript (const QString & userPrompt, const QString & folderPath, const QString & os)
Wygeneruj skrypt na podstawie promptu.
Parameters
userPrompt polecenie od u┐ytkownika (polski/angielski)
folderPath £cie┐ka do folderu docelowego
os identyfikator systemu ("Windows" lub "Linux")
Wynik zostanie dostarczony asynchronicznie:
scriptReady(zawiera skrypt) lub
errorOccurred(z komunikatem b│Ļdu)
Zwr¾µ uwagĻ:
Funkcja wysy│a JSON do lokalnego serwera (Ollama) Ś patrz API_URL i MODEL.
Obs│uga b│Ļd¾w i timeout jest implementowana w llmclient.cpp.
Definition at line 19 of file llmclient.cpp.
{
    // ----------------------------------------------------------
    // Definicja system prompt (kryterium: Definicja system prompt)
    // ----------------------------------------------------------
    QString systemPrompt;
    if (os == "Windows") {
        systemPrompt = "Jestes generatorem skryptow PowerShell. "
                       "Generuj TYLKO czysty kod PowerShell. "
                       "Uzywaj TYLKO Move-Item do przenoszenia plikow. "
                       "NIGDY nie uzywaj Remove-Item. "
                       "Aby przeniesc plik DO folderu uzyj: Move-Item -Path $file -Destination $folderPath gdzie $folderPath to FOLDER nie pelna sciezka pliku. "
                       "Aby filtrowac wiele rozszerzen ZAWSZE uzywaj osobnego Get-ChildItem dla kazdego rozszerzenia osobno. "
                       "Nie usuwaj rozszerzen z plikow"
                       "Sprawdzaj czy folder istnieje przed przeniesieniem plikow jezeli nie to stworz go w $folderPath"
                       "Aby utworzyc folder: New-Item -ItemType Directory -Force -Path $folder. "
                       "Po kazdym przeniesieniu: Write-Host 'MOVED: plik -> cel'. "
                       "Nie dodawaj opisow ani komentarzy.";
                       "ZAKAZANE: -Filter '*.jpg, *.png' (przecinek w filtrze jest BLEDNY)";
    } else {
        systemPrompt = "Jestes generatorem skryptow Bash. "
                       "Generuj TYLKO czysty kod Bash bez opisow, bez komentarzy. "
                       "Uzywaj TYLKO mv do przenoszenia plikow. "
                       "NIGDY nie uzywaj rm -rf. "
                       "Aby utworzyc folder uzyj: mkdir -p. "
                       "Po kazdym przeniesieniu uzyj: echo 'MOVED: plik -> cel'. "
                       "NIE pisz slowa MOVED bez echo. "
                       "Nie dodawaj zadnych opisow ani komentarzy poza kodem.";
                       "- Dla folderu A-Z uzyj: for letter in {A..Z}; do mkdir -p \"$sourcePath/$letter\"; done\n";
    }
    QString fullPrompt = QString("Folder: %1\nPolecenie: %2")
                             .arg(folderPath, userPrompt);
    QJsonObject json;
    json["model"] = MODEL;
    json["system"] = systemPrompt;
    json["prompt"] = fullPrompt;
    json["stream"] = false;
    json["options"] = QJsonObject{{"num_predict", 1024}};
    QString apiUrl = QString::fromUtf8(qgetenv("OLLAMA_API_URL"));
    if (apiUrl.isEmpty()) apiUrl = API_URL;
    QUrl url(apiUrl);
    QNetworkRequest request(url);
    request.setHeader(QNetworkRequest::ContentTypeHeader, "application/json; charset=utf-8");
    QByteArray data = QJsonDocument(json).toJson();
    QNetworkReply *reply = manager->post(request, data);
    /*QTimer *netTimer = new QTimer(reply);
    netTimer->setSingleShot(true);
    netTimer->start(180000);
    connect(netTimer, &QTimer::timeout, reply, [reply, this]() {
        if (!reply->isFinished()) {
            reply->abort();
            emit errorOccurred("Timeout: brak odpowiedzi od serwera LLM (Ollama) po 180 sekundach.");
        }
    });*/
    connect(reply, &QNetworkReply::finished, this, [this, reply]() {
        if (reply->error() != QNetworkReply::NoError) {
            emit errorOccurred(QString("Blad polaczenia z Ollama: %1")
                               .arg(reply->errorString()));
            reply->deleteLater();
            return;
        }
        // ----------------------------------------------------------
        // Parsowanie odpowiedzi i czyszczenie skryptu
        // ----------------------------------------------------------
        QByteArray raw = reply->readAll();
        QString script;
        QJsonParseError parseError;
        QJsonDocument doc = QJsonDocument::fromJson(raw, &parseError);
        if (!doc.isNull() && doc.isObject()) {
            QJsonObject obj = doc.object();
            if (obj.contains("response")) {
                script = obj.value("response").toString();
            } else if (obj.contains("text")) {
                script = obj.value("text").toString();
            } else {
                script = QString::fromUtf8(raw);
            }
        } else {
            script = QString::fromUtf8(raw);
        }
        // ZMIANA: Bezpieczniejsze czyszczenie
        // 1. Usu┼ä bloki <think>...</think>
        script.remove(QRegularExpression("<think>[\\s\\S]*?</think>",
                                  QRegularExpression::CaseInsensitiveOption));
        // 2. Usu┼ä bloki markdown ```powershell...``` lub ```bash...```
        // Wzorzec: ``` opcjonalny j─Özyk (powershell/bash) dowolny tekst ```
        script.remove(QRegularExpression("```(?:powershell|bash)?\\s*\\n",
                                        QRegularExpression::CaseInsensitiveOption));
        script.remove(QRegularExpression("\\n?```\\s*$",
                                        QRegularExpression::CaseInsensitiveOption));
        script.remove(QRegularExpression("^```\\s*",
                                        QRegularExpression::CaseInsensitiveOption));
        // 3. Usu┼ä tylko linie CA┼üKOWICIE opisowe (nie dotykaj kodu)
        QStringList lines = script.split(QRegularExpression("\\r?\\n"));
        QStringList cleanLines;
        for (const QString &line : lines) {
            QString trimmed = line.trimmed();
            // Pomi┼ä puste linie
            if (trimmed.isEmpty()) {
                continue;
            }
            // Pomi┼ä tylko linie komentarzy
            if (trimmed.startsWith('#') && !trimmed.contains("MOVED:")) {
                continue;
            }
            // Pomi┼ä linie zaczynaj─ģce si─Ö od opisowych s┼é├│w (TYLKO je┼øli nie ma znaku $ lub Move-Item)
            bool isDescriptiveLine = false;
            QStringList descriptiveStarts = {"First", "Next", "Now", "This", "The", "Note", "Please",
                                              "Uwaga", "Najpierw", "Nastepnie", "Teraz", "Prosze",
                                              "Here", "To", "You", "We"};
            for (const QString &desc : descriptiveStarts) {
                if (trimmed.startsWith(desc, Qt::CaseInsensitive) &&
                    !trimmed.contains("$") &&
                    !trimmed.contains("Move-Item") &&
                    !trimmed.contains("Get-ChildItem") &&
                    !trimmed.contains("New-Item") &&
                    !trimmed.contains("mkdir") &&
                    !trimmed.contains("mv") &&
                    !trimmed.contains("echo")) {
                    isDescriptiveLine = true;
                    break;
                }
            }
            if (isDescriptiveLine) {
                continue;
            }
            // Dodaj lini─Ö do oczyszczonego skryptu
            cleanLines.append(line); // Zachowaj oryginalne wci─Öcia!
        }
        script = cleanLines.join("\n").trimmed();
        // 4. Napraw brakuj─ģce nawiasy klamrowe
        int openBraces = script.count('{');
        int closeBraces = script.count('}');
        while (closeBraces < openBraces) {
            script += "\n}";
            closeBraces++;
        }
        // 5. Sprawd┼║ czy skrypt nie jest pusty
        if (script.isEmpty() || script.length() < 10) {
            emit errorOccurred(QString("Otrzymano pusty lub zbyt krotki skrypt od modelu LLM.\n\nSurowa odpowiedz:\n%1")
                              .arg(QString::fromUtf8(raw).left(500)));
        } else {
            emit scriptReady(script);
        }
        reply->deleteLater();
    });
}
References API_URL, errorOccurred(), manager, MODEL, and scriptReady().
Referenced by FileOrganizerTests::test_llmClient_emitsError_whenNoOllama().
scriptReady
void LlmClient::scriptReady (const QString & script) signal
Emitted when a cleaned script is ready.
Referenced by generateScript(), MainWindow::MainWindow(), and FileOrganizerTests::test_llmClient_emitsError_whenNoOllama().
Member Data Documentation
API_URL
const QString LlmClient::API_URL = "http://localhost:11434/api/generate" private
Definition at line 58 of file llmclient.h.
Referenced by generateScript().
manager
QNetworkAccessManager* LlmClient::manager private
Definition at line 56 of file llmclient.h.
Referenced by generateScript(), and LlmClient().
MODEL
const QString LlmClient::MODEL = "SpeakLeash/bielik-11b-v3.0-instruct:Q4_K_M" private
Definition at line 60 of file llmclient.h.
Referenced by generateScript().
The documentation for this class was generated from the following files:
llmclient.h
llmclient.cpp