Inteligentny Organizator Plików: ScriptRunner Class Reference
ScriptRunner Class Reference
Klasa do uruchamiania skryptów systemowych.
#include <scriptrunner.h>
Signals
void finished (const QString &output)
void errorOccurred (const QString &error)
Public Member Functions
ScriptRunner (QObject *parent=nullptr)
Konstruktor ScriptRunner.
void runScript (const QString &scriptContent)
Static Public Member Functions
static QString detectOS ()
Wykrywa system operacyjny.
Private Attributes
QProcess * process
Detailed Description
Klasa do uruchamiania skryptów systemowych.
Definition at line 10 of file scriptrunner.h.
Constructor & Destructor Documentation
ScriptRunner()
ScriptRunner::ScriptRunner (QObject * parent = nullptr) explicit
Konstruktor ScriptRunner.
Definition at line 11 of file scriptrunner.cpp.
                                          : QObject(parent)
{
    process = new QProcess(this);
}
References process.
Member Function Documentation
detectOS()
QString ScriptRunner::detectOS () static
Wykrywa system operacyjny.
Definition at line 19 of file scriptrunner.cpp.
{
#ifdef Q_OS_WIN
    return "Windows";
#else
    return "Linux";
#endif
}
Referenced by MainWindow::on_previewButton_clicked(), runScript(), FileOrganizerTests::test_detectOS_isWindows(), FileOrganizerTests::test_detectOS_notEmpty(), and FileOrganizerTests::test_detectOS_validValue().
errorOccurred
void ScriptRunner::errorOccurred (const QString & error) signal
Referenced by MainWindow::MainWindow(), runScript(), and FileOrganizerTests::test_scriptExecution_echo().
finished
void ScriptRunner::finished (const QString & output) signal
Referenced by MainWindow::MainWindow(), runScript(), and FileOrganizerTests::test_scriptExecution_echo().
runScript()
void ScriptRunner::runScript (const QString & scriptContent)
Definition at line 29 of file scriptrunner.cpp.
{
    QString os = detectOS();
    QString suffix = (os == "Windows") ? ".ps1" : ".sh";
    QTemporaryFile tmpFile;
    tmpFile.setFileTemplate(QDir::tempPath() + "/organizer_XXXXXX" + suffix);
    tmpFile.setAutoRemove(false);
    if (!tmpFile.open()) {
        emit errorOccurred("Nie można utworzyć pliku tymczasowego!");
        return;
    }
    // Na Windows dopisujemy BOM, aby PowerShell poprawnie czytał polskie znaki w starszych konfiguracjach
#ifdef Q_OS_WIN
    tmpFile.write("\xEF\xBB\xBF");
#endif
    tmpFile.write(scriptContent.toUtf8());
    tmpFile.close();
    QString scriptPath = tmpFile.fileName();
    // Upewnij się że nie ma starych połączeń
    process->disconnect();
    process->setProcessChannelMode(QProcess::MergedChannels);
    connect(process, QOverload<int, QProcess::ExitStatus>::of(&QProcess::finished),
            this, [this, scriptPath](int exitCode, QProcess::ExitStatus) {
                QString output = process->readAllStandardOutput();
                QString errors = process->readAllStandardError();
                // Usuń plik tymczasowy
                QFile::remove(scriptPath);
                if (!errors.isEmpty()) {
                    emit errorOccurred(errors.trimmed());
                } else {
                    emit finished(output.trimmed());
                }
            });
    // Timeout wykonania procesu (60s)
    QTimer *procTimer = new QTimer(process);
    procTimer->setSingleShot(true);
    procTimer->start(60000);
    connect(procTimer, &QTimer::timeout, process, [this, scriptPath]() {
        if (process->state() != QProcess::NotRunning) {
            process->kill();
            QFile::remove(scriptPath);
            emit errorOccurred("Przekroczono czas wykonania skryptu (timeout).");
        }
    });
#ifdef Q_OS_WIN
    // Uruchom PowerShell z bypass execution policy
    process->start("powershell", {"-ExecutionPolicy", "Bypass", "-File", scriptPath});
#else
    // Nadaj prawa wykonywania i uruchom bash
    QFile::setPermissions(scriptPath, QFile::permissions(scriptPath) | QFileDevice::ExeUser);
    process->start("bash", {scriptPath});
#endif
}
References detectOS(), errorOccurred(), finished(), and process.
Referenced by FileOrganizerTests::test_scriptExecution_echo().
Member Data Documentation
process
QProcess* ScriptRunner::process private
Definition at line 24 of file scriptrunner.h.
Referenced by runScript(), and ScriptRunner().
The documentation for this class was generated from the following files:
scriptrunner.h
scriptrunner.cpp