Inteligentny Organizator Plików: MainWindow Class Reference
MainWindow Class Reference
Główne okno aplikacji FileOrganizer.
#include <mainwindow.h>
Public Member Functions
MainWindow (QWidget *parent=nullptr)
Konstruktor MainWindow.
~MainWindow ()
Private Slots
void on_browseButton_clicked ()
Otwiera dialog wyboru folderu.
void on_previewButton_clicked ()
Generuje podgląd skryptu bez wykonywania.
void on_runButton_clicked ()
Wykonuje wygenerowany skrypt.
void onScriptReady (const QString &script)
Obsługuje gotowy skrypt od LLM.
void onScriptFinished (const QString &output)
Obsługuje wynik wykonania skryptu.
void onError (const QString &error)
Obsługuje błędy.
Private Member Functions
void setButtonsEnabled (bool enabled)
Włącza/wyłącza przyciski podczas operacji.
Private Attributes
Ui::MainWindow * ui
LlmClient * llmClient
ScriptRunner * scriptRunner
QString currentScript
Detailed Description
Główne okno aplikacji FileOrganizer.
Definition at line 15 of file mainwindow.h.
Constructor & Destructor Documentation
MainWindow()
MainWindow::MainWindow (QWidget * parent = nullptr)
Konstruktor MainWindow.
MAPOWANIE KRYTERIÓW:
Interfejs graficzny: pola folderPathEdit, commandEdit, reportEdit (UI).
Komunikacja z LLM: wywołanie llmClient->generateScript(...).
Obsługa błędów: slot onError wyświetla komunikaty użytkownikowi.
Automatyczne wykonanie skryptu: delegowane do ScriptRunner::runScript.
Definition at line 15 of file mainwindow.cpp.
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    ui->setupUi(this);
    setWindowTitle("🗂️ Inteligentny Organizator Plików");
    llmClient = new LlmClient(this);
    scriptRunner = new ScriptRunner(this);
    connect(llmClient, &LlmClient::scriptReady,
            this, &MainWindow::onScriptReady);
    connect(llmClient, &LlmClient::errorOccurred,
            this, &MainWindow::onError);
    connect(scriptRunner, &ScriptRunner::finished,
            this, &MainWindow::onScriptFinished);
    connect(scriptRunner, &ScriptRunner::errorOccurred,
            this, &MainWindow::onError);
}
References LlmClient::errorOccurred(), ScriptRunner::errorOccurred(), ScriptRunner::finished(), llmClient, MainWindow(), onError(), onScriptFinished(), onScriptReady(), LlmClient::scriptReady(), scriptRunner, and ui.
Referenced by MainWindow().
~MainWindow()
MainWindow::~MainWindow ()
Definition at line 35 of file mainwindow.cpp.
{
    delete ui;
}
References ui.
Member Function Documentation
on_browseButton_clicked
void MainWindow::on_browseButton_clicked () private slot
Otwiera dialog wyboru folderu.
UI: pole folderPathEdit -> miejsce gdzie użytkownik wskazuje folder.
Definition at line 45 of file mainwindow.cpp.
{
    QString folder = QFileDialog::getExistingDirectory(
        this, "Wybierz folder", QDir::homePath());
    if (!folder.isEmpty()) {
        ui->folderPathEdit->setText(folder);
    }
}
References ui.
on_previewButton_clicked
void MainWindow::on_previewButton_clicked () private slot
Generuje podgląd skryptu bez wykonywania.
Pobiera commandEdit i folderPathEdit, waliduje wejście (kryterium: ostrzeżenie przy braku danych).
Uruchamia LlmClient::generateScript (kryterium: generowanie na podstawie parametrów użytkownika).
Definition at line 60 of file mainwindow.cpp.
{
    if (ui->folderPathEdit->text().isEmpty()) {
        QMessageBox::warning(this, "Brak folderu",
                             "Proszę wybrać folder do organizacji!");
        return;
    }
    if (ui->commandEdit->toPlainText().isEmpty()) {
        QMessageBox::warning(this, "Brak polecenia",
                             "Proszę wpisać polecenie!");
        return;
    }
    ui->reportEdit->setPlainText("⏳ Generowanie skryptu...");
    setButtonsEnabled(false);
    llmClient->generateScript(
        ui->commandEdit->toPlainText(),
        ui->folderPathEdit->text(),
        ScriptRunner::detectOS()
        );
}
References ScriptRunner::detectOS(), llmClient, setButtonsEnabled(), and ui.
on_runButton_clicked
void MainWindow::on_runButton_clicked () private slot
Wykonuje wygenerowany skrypt.
Aktualnie wymaga potwierdzenia użytkownika; aby mieć pełne "automatyczne wykonanie", usuń dialog QMessageBox::question (zmiana wymagana ręcznie).
Definition at line 89 of file mainwindow.cpp.
{
    if (currentScript.isEmpty()) {
        QMessageBox::warning(this, "Brak skryptu",
                             "Najpierw wygeneruj podgląd skryptu!");
        return;
    }
    QMessageBox::StandardButton reply = QMessageBox::question(
        this, "Potwierdzenie",
        "Czy na pewno chcesz wykonać operacje na plikach?",
        QMessageBox::Yes | QMessageBox::No);
    if (reply == QMessageBox::Yes) {
        ui->reportEdit->setPlainText("⏳ Wykonywanie skryptu...");
        setButtonsEnabled(false);
        scriptRunner->runScript(currentScript);
    }
}
References currentScript, scriptRunner, setButtonsEnabled(), and ui.
onError
void MainWindow::onError (const QString & error) private slot
Obsługuje błędy.
Informuje użytkownika o problemach z dostępnością usługi / wykonania.
Definition at line 137 of file mainwindow.cpp.
{
    ui->reportEdit->setPlainText("❌ BŁĄD:\n\n" + error);
    setButtonsEnabled(true);
    QMessageBox::critical(this, "Błąd", error);
}
References setButtonsEnabled(), and ui.
Referenced by MainWindow().
onScriptFinished
void MainWindow::onScriptFinished (const QString & output) private slot
Obsługuje wynik wykonania skryptu.
Definition at line 125 of file mainwindow.cpp.
{
    ui->reportEdit->setPlainText("✅ WYKONANO!\n\n" + output);
    setButtonsEnabled(true);
    currentScript.clear();
}
References currentScript, setButtonsEnabled(), and ui.
Referenced by MainWindow().
onScriptReady
void MainWindow::onScriptReady (const QString & script) private slot
Obsługuje gotowy skrypt od LLM.
Odbiera oczyszczony skrypt i wyświetla podgląd (kryterium: generacja skryptu).
Definition at line 114 of file mainwindow.cpp.
{
    currentScript = script;
    ui->reportEdit->setPlainText("📋 PODGLĄD SKRYPTU:\n\n" + script +
                                 "\n\n✅ Kliknij 'Wykonaj' aby uruchomić.");
    setButtonsEnabled(true);
}
References currentScript, setButtonsEnabled(), and ui.
Referenced by MainWindow().
setButtonsEnabled()
void MainWindow::setButtonsEnabled (bool enabled) private
Włącza/wyłącza przyciski podczas operacji.
Definition at line 147 of file mainwindow.cpp.
{
    ui->previewButton->setEnabled(enabled);
    ui->runButton->setEnabled(enabled);
    ui->browseButton->setEnabled(enabled);
}
References ui.
Referenced by on_previewButton_clicked(), on_runButton_clicked(), onError(), onScriptFinished(), and onScriptReady().
Member Data Documentation
currentScript
QString MainWindow::currentScript private
Definition at line 35 of file mainwindow.h.
Referenced by on_runButton_clicked(), onScriptFinished(), and onScriptReady().
llmClient
LlmClient* MainWindow::llmClient private
Definition at line 33 of file mainwindow.h.
Referenced by MainWindow(), and on_previewButton_clicked().
scriptRunner
ScriptRunner* MainWindow::scriptRunner private
Definition at line 34 of file mainwindow.h.
Referenced by MainWindow(), and on_runButton_clicked().
ui
Ui::MainWindow* MainWindow::ui private
Definition at line 32 of file mainwindow.h.
Referenced by MainWindow(), on_browseButton_clicked(), on_previewButton_clicked(), on_runButton_clicked(), onError(), onScriptFinished(), onScriptReady(), setButtonsEnabled(), and ~MainWindow().
The documentation for this class was generated from the following files:
mainwindow.h
mainwindow.cpp